[package]
name = "libwallet"
version = "0.1.0"
authors = ["Daniel Olano <me@olanod.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.51"
codec = { version = "2.3.1", package = "parity-scale-codec", optional = true }
sp-core = { version = "3.0.0", default-features = false, features = ["full_crypto"] }
thiserror = { version = "1.0.30", optional = true }

[dev-dependencies]
clap = "2.33.3"
async-std = { version = "1.10.0", features = ["attributes"] }

[features]
default = ["std", "simple", "substrate"]
substrate = ["codec"]
simple = []
std = [
	"thiserror",
	"sp-core/std",
]
